// Mocks generated by Mockito 5.4.4 from annotations
// in frontend_flutter_main/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend_flutter_main/core/services/token_manager_service.dart'
    as _i6;
import 'package:frontend_flutter_main/features/auth/data/datasources/auth_local_data_source.dart'
    as _i5;
import 'package:frontend_flutter_main/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:frontend_flutter_main/features/auth/data/dtos/auth_session_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthSessionDto_0 extends _i1.SmartFake
    implements _i2.AuthSessionDto {
  _FakeAuthSessionDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthSessionDto> loginWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #loginWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthSessionDto>.value(_FakeAuthSessionDto_0(
          this,
          Invocation.method(
            #loginWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthSessionDto>);

  @override
  _i4.Future<_i2.AuthSessionDto> loginWithApple() => (super.noSuchMethod(
        Invocation.method(
          #loginWithApple,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthSessionDto>.value(_FakeAuthSessionDto_0(
          this,
          Invocation.method(
            #loginWithApple,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthSessionDto>);

  @override
  _i4.Future<_i2.AuthSessionDto> loginWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthSessionDto>.value(_FakeAuthSessionDto_0(
          this,
          Invocation.method(
            #loginWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthSessionDto>);

  @override
  _i4.Future<_i2.AuthSessionDto> registerWithEmail(
    String? email,
    String? password, {
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [
            email,
            password,
          ],
          {
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue: _i4.Future<_i2.AuthSessionDto>.value(_FakeAuthSessionDto_0(
          this,
          Invocation.method(
            #registerWithEmail,
            [
              email,
              password,
            ],
            {
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthSessionDto>);

  @override
  _i4.Future<void> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout(String? accessToken) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [accessToken],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i5.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveSession(_i2.AuthSessionDto? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthSessionDto?> getSession() => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthSessionDto?>.value(),
      ) as _i4.Future<_i2.AuthSessionDto?>);

  @override
  _i4.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasSession() => (super.noSuchMethod(
        Invocation.method(
          #hasSession,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [TokenManagerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenManagerService extends _i1.Mock
    implements _i6.TokenManagerService {
  MockTokenManagerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggingOut => (super.noSuchMethod(
        Invocation.getter(#isLoggingOut),
        returnValue: false,
      ) as bool);

  @override
  bool get hasToken => (super.noSuchMethod(
        Invocation.getter(#hasToken),
        returnValue: false,
      ) as bool);

  @override
  void resetLogoutState() => super.noSuchMethod(
        Invocation.method(
          #resetLogoutState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> save(String? token) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #loadFromStorage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
