// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY99vVX0nwb1boVqHic3zVdLYl4aKqt5o',
    appId: '1:508456394522:android:fb4d236c0a90334f50d6a3',
    messagingSenderId: '508456394522',
    projectId: 'trackspend-e87ab',
    storageBucket: 'trackspend-e87ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr1e2QA7QB89AI52_qZxDc57lB1w0qsjI',
    appId: '1:508456394522:ios:6168f43756a96aec50d6a3',
    messagingSenderId: '508456394522',
    projectId: 'trackspend-e87ab',
    storageBucket: 'trackspend-e87ab.firebasestorage.app',
    androidClientId: '508456394522-jssmp98sk3bmo9jt584n7lmb6uhvmno9.apps.googleusercontent.com',
    iosClientId: '508456394522-d56g5o1ll4stt35cumd49pvn76gsl78j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutterMain',
  );

}