// Mocks generated by Mockito 5.4.4 from annotations
// in frontend_flutter_main/test/features/auth/presentation/notifiers/auth_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:frontend_flutter_main/core/services/api_service_v2.dart'
    as _i16;
import 'package:frontend_flutter_main/core/services/token_manager_service.dart'
    as _i15;
import 'package:frontend_flutter_main/features/auth/application/use_cases/forgot_password_use_case.dart'
    as _i12;
import 'package:frontend_flutter_main/features/auth/application/use_cases/get_cached_session_use_case.dart'
    as _i13;
import 'package:frontend_flutter_main/features/auth/application/use_cases/login_with_apple_use_case.dart'
    as _i9;
import 'package:frontend_flutter_main/features/auth/application/use_cases/login_with_email_use_case.dart'
    as _i10;
import 'package:frontend_flutter_main/features/auth/application/use_cases/login_with_google_use_case.dart'
    as _i3;
import 'package:frontend_flutter_main/features/auth/application/use_cases/logout_use_case.dart'
    as _i14;
import 'package:frontend_flutter_main/features/auth/application/use_cases/register_with_email_use_case.dart'
    as _i11;
import 'package:frontend_flutter_main/features/auth/domain/core/either.dart'
    as _i5;
import 'package:frontend_flutter_main/features/auth/domain/entities/auth_session.dart'
    as _i7;
import 'package:frontend_flutter_main/features/auth/domain/failures/auth_failure.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginWithGoogleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithGoogleUseCase extends _i1.Mock
    implements _i3.LoginWithGoogleUseCase {
  MockLoginWithGoogleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>.value(
                _i8.dummyValue<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>);
}

/// A class which mocks [LoginWithAppleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithAppleUseCase extends _i1.Mock
    implements _i9.LoginWithAppleUseCase {
  MockLoginWithAppleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>.value(
                _i8.dummyValue<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>);
}

/// A class which mocks [LoginWithEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithEmailUseCase extends _i1.Mock
    implements _i10.LoginWithEmailUseCase {
  MockLoginWithEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>.value(
                _i8.dummyValue<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>);
}

/// A class which mocks [RegisterWithEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterWithEmailUseCase extends _i1.Mock
    implements _i11.RegisterWithEmailUseCase {
  MockRegisterWithEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>> call(
    String? email,
    String? password, {
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
          {
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>.value(
                _i8.dummyValue<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
            {
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession>>);
}

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i12.ForgotPasswordUseCase {
  MockForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, void>> call(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [email],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.AuthFailure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, void>>);
}

/// A class which mocks [GetCachedSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedSessionUseCase extends _i1.Mock
    implements _i13.GetCachedSessionUseCase {
  MockGetCachedSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession?>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession?>>.value(
                _i8.dummyValue<_i5.Either<_i6.AuthFailure, _i7.AuthSession?>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, _i7.AuthSession?>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i14.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AuthFailure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.AuthFailure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.AuthFailure, void>>);
}

/// A class which mocks [TokenManagerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenManagerService extends _i1.Mock
    implements _i15.TokenManagerService {
  MockTokenManagerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggingOut => (super.noSuchMethod(
        Invocation.getter(#isLoggingOut),
        returnValue: false,
      ) as bool);

  @override
  bool get hasToken => (super.noSuchMethod(
        Invocation.getter(#hasToken),
        returnValue: false,
      ) as bool);

  @override
  void resetLogoutState() => super.noSuchMethod(
        Invocation.method(
          #resetLogoutState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> save(String? token) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #loadFromStorage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ApiServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceV2 extends _i1.Mock implements _i16.ApiServiceV2 {
  MockApiServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
}
