import 'package:firebase_core/firebase_core.dart';

import '../../firebase_options.dart';

/// Firebase configuration.
///
/// **Initialization** uses [DefaultFirebaseOptions] from `lib/firebase_options.dart`,
/// generated by the FlutterFire CLI. Do not edit that file by hand.
///
/// **To (re)configure Firebase:**
/// 1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
/// 2. Run: `flutterfire configure`
/// 3. In Firebase Console, ensure you have:
///    - An **Android** app with package name matching `android/app/build.gradle.kts` (e.g. `com.example.frontend_flutter_main` or `com.olvora.expense`)
///    - An **iOS** app with bundle ID matching Xcode’s `PRODUCT_BUNDLE_IDENTIFIER` (e.g. `com.olvora.expense`). If you use a different bundle ID than the one in `firebase_options.dart`, add that app in Firebase and run `flutterfire configure` again.
/// 4. After adding/changing apps, run `flutterfire configure` to regenerate `firebase_options.dart`, `google-services.json`, and `GoogleService-Info.plist`.
class FirebaseConfig {
  /// Current platform options (from FlutterFire-generated firebase_options.dart).
  static FirebaseOptions get currentPlatform =>
      DefaultFirebaseOptions.currentPlatform;

  @Deprecated('Use DefaultFirebaseOptions.currentPlatform or FirebaseConfig.currentPlatform')
  static FirebaseOptions get defaultOptions => currentPlatform;
}
